### ISSUE TITLE
Experiments are not accessable

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-mechanical-vibration-iitg#1]
Experiments are not accessable. All experiments are pointng to 202.141.81.60 ip address

**Comment by sanchita-dixit** [comment]
All experiments have a download link for some executable file which is pointing to the guwahati servers hence the IP. Since they are directing to their servers and the files are unable to download from the links given, we are unable to do anything. I also checked the [github lab sources](https://github.com/virtual-labs/virtual-lab-for-mechanical-vibrations-iitg/blob/master/src/ForcedContinuousExperiment.html) for this lab and they also have a href driected to their servers itself. We dont have these exe file sources with us. For now I have changed the experiment URLs to one page before where it is not showing any inaccessible page for now.

**Comment by sravanthimodepu** [comment]
Closing the issue.
